data_source nyc_taxi_snowflake:
  type: snowflake
  username: ${SF_USER}
  password: ${SF_PASSWORD}
  account: ${SF_ACCOUNT}
  database: NYC_TAXI
  schema: GOLD
  warehouse: COMPUTE_WH
  role: ACCOUNTADMIN
